name       : putty
version    : 0.70
release    : 1
source     :
    - https://the.earth.li/~sgtatham/putty/latest/putty-0.70.tar.gz : bb8aa49d6e96c5a8e18a057f3150a1695ed99a24eef699e783651d1f24e7b0be
license    : MIT
component  : network.remote
summary    : PuTTY is a free implementation of SSH and Telnet
description: |
    PuTTY is a free implementation of SSH and Telnet
builddeps  : 
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/putty.desktop $installdir/usr/share/applications/putty.desktop
    install -D -m 00644 $pkgfiles/putty.png $installdir/usr/share/pixmaps/putty.png
    install -D -m 00644 $pkgfiles/putty.xpm $installdir/usr/share/pixmaps/putty.xpm
