name       : putty
version    : 0.7.1
release    : 2
source     :
    - https://the.earth.li/~sgtatham/putty/latest/putty-0.71.tar.gz : 2f931ce2f89780cc8ca7bbed90fcd22c44515d2773f5fa954069e209b48ec6b8
license    : MIT
component  : network.remote
summary    : PuTTY is a free implementation of SSH and Telnet
description: |
    PuTTY is a free implementation of SSH and Telnet
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/putty.desktop $installdir/usr/share/applications/putty.desktop
    install -D -m 00644 $pkgfiles/putty.png $installdir/usr/share/pixmaps/putty.png
    install -D -m 00644 $pkgfiles/putty.xpm $installdir/usr/share/pixmaps/putty.xpm
