name       : putty
version    : '0.76'
release    : 10
source     :
    - https://the.earth.li/~sgtatham/putty/latest/putty-0.76.tar.gz : 547cd97a8daa87ef71037fab0773bceb54a8abccb2f825a49ef8eba5e045713f
license    : MIT
component  : network.remote
summary    : PuTTY is a free implementation of SSH and Telnet
description: |
    PuTTY is a free implementation of SSH and Telnet
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/putty.desktop $installdir/usr/share/applications/putty.desktop
    install -D -m 00644 $pkgfiles/putty.png $installdir/usr/share/pixmaps/putty.png
    install -D -m 00644 $pkgfiles/putty.xpm $installdir/usr/share/pixmaps/putty.xpm
